import { HeaderObject } from "simple-table-core";

export const getSpreadsheetHeaders = (additionalColumns: HeaderObject[] = []): HeaderObject[] => [
  {
    accessor: "principal",
    label: "Principal",
    width: "1fr",
    minWidth: 100,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "sum" },
  },
  {
    accessor: "interestRate",
    label: "Interest Rate %",
    width: "1fr",
    minWidth: 110,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "average" },
  },
  {
    accessor: "monthlyPayment",
    label: "Monthly Payment",
    width: "1fr",
    minWidth: 120,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "sum" },
  },
  {
    accessor: "remainingBalance",
    label: "Remaining Balance",
    width: "1fr",
    minWidth: 130,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "sum" },
  },
  {
    accessor: "totalPaid",
    label: "Total Paid",
    width: "1fr",
    minWidth: 110,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "sum" },
  },
  {
    accessor: "interestPaid",
    label: "Interest Paid",
    width: "1fr",
    minWidth: 110,
    align: "right",
    isEditable: true,
    type: "number",
    aggregation: { type: "sum" },
  },
  ...additionalColumns,
];
